[tool.black]
line-length = 120
target-verison = ['py39']

[tool.isort]
line_length = 120
force_single_line = false
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
force_sort_within_sections = true
# Compatibility with black. Taken directly from the black docs here:
# https://black.readthedocs.io/en/stable/the_black_code_style.html
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
profile = "black"
